use [50_days_sql_challenge];

--- 1. Find products sold in the highest quantity. ----

select od.product_id,p.product_name,sum(od.quantity) as total_quantity
from clean_order_details od  
inner join clean_products p on od.product_id = p.product_id
group by od.product_id,p.product_name
order by total_quantity desc;

--- 2. Find the least selling products.  -----

select od.product_id,p.product_name,sum(od.quantity) as total_quantity
from clean_order_details od  
right join clean_products p on od.product_id = p.product_id
group by od.product_id,p.product_name
order by total_quantity ;
  
--- 3. Find revenue generated by each product. -----

select od.product_id,p.product_name,sum(od.quantity * p.price) as total_revenue
from clean_order_details od  
inner join clean_products p on od.product_id = p.product_id
group by od.product_id,p.product_name
order by total_revenue desc;

--- 4. Find total sales for each category. -----

select p.category,sum(od.quantity * p.price) as total_sales
from clean_order_details od  
inner join clean_products p on od.product_id = p.product_id
group by p.category
order by total_sales desc;
 
--- 5. Find the highest priced product that was sold. -----

select DISTINCT TOP 1 od.product_id,p.product_name,p.price
from clean_order_details od  
inner join clean_products p on od.product_id = p.product_id
order by p.price desc;

--- 6. Find average product price category-wise.  -----

select category, avg(price) as avg_product_price
from clean_products
group by category
order by avg_product_price desc;

--- 7. Find daily quantity sold for each product.  -----

select  o.order_date,od.product_id,p.product_name,sum(od.quantity) as total_quantity
from clean_order_details od  
inner join clean_products p on od.product_id = p.product_id
inner join clean_orders o on o.order_id = od.order_id
group by o.order_date,od.product_id,p.product_name
order by o.order_date;