use [50_days_sql_challenge];

--- 1. Find total business revenue. ------------

select sum(payment_amount) as total_business_revenue
from clean_payments 

--- 2. Find daily revenue. ------------

select payment_date,sum(payment_amount) as daily_revenue
from clean_payments 
group by payment_date
order by payment_date;

--- 3. Find monthly revenue trend. ------------

select month(o.order_date) as month_no,
       datename(month, o.order_date) as month_name, 
       sum(p.payment_amount) as monthly_revenue
from clean_orders o
inner join clean_payments p on o.order_id = p.order_id
group by month(o.order_date), datename(month, o.order_date)
order by month_no;


--- 4. Find revenue generated by each product. ------------

select p.product_id,p.product_name, sum(p.price * od.quantity) as productwise_revenue
from clean_products p  
inner join clean_order_details od  on p.product_id = od.product_id
group by p.product_id,p.product_name
order by productwise_revenue desc;

--- 5. Find customer-wise revenue. ------------

select c.customer_id, c.customer_name, c.city,sum(p.payment_amount) as customerwise_revenue
from clean_customers c  
inner join clean_orders o on c.customer_id = o.customer_id
inner join clean_payments p on o.order_id = p.order_id
group by c.customer_id, c.customer_name, c.city
order by customerwise_revenue desc;

--- 6. Find category-wise revenue. ------------

select p.category, sum(p.price * od.quantity) as total_revenue
from clean_products p  
inner join clean_order_details od  on p.product_id = od.product_id
group by p.category
order by total_revenue desc;


--- 7. Question: Find days generating highest revenue. ------------

select payment_date,sum(payment_amount) as total_revenue
from clean_payments
group by payment_date
order by total_revenue desc;